### PR TITLE
Adding a working dockerfile

### PR DESCRIPTION
**Pull request by matthewbaggett**
I'd love to be able to use this as a docker container, so I made this. Suggestions welcome!

### CODE REVIEW

**Comment by gdude2002** [comment]
Wouldn't it be preferable to have a Dockerfile that does all the git work instead? You wouldn't even need to manually clone the repo then

**Comment by xhacker** [comment]
Thank you. Can you remove the last empty line (there are two empty lines now) in Dockerfile?

**Comment by matthewbaggett** [comment]
@xhacker Absolutely. One moment.

**Comment by matthewbaggett** [comment]
@gdude2002 That would require the docker instance to have git installed into it, which would make the resulting image larger than it needs to be. The less dead weight in the resulting system image the better.

**Comment by matthewbaggett** [comment]
All done, @xhacker

**Comment by xhacker** [comment]
@matthewbaggett: Can you squash the two commits, then I’ll merge it. Thank you!

**Comment by matthewbaggett** [comment]
Squashed. I think its good now, @xhacker.

**Comment by xhacker** [comment]
Merged, thank you!

**Pull request merged**
